language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci
before_script:
  - psql -c 'freshly' -U postgres
script:
  - npm test
  - npm run build-client

before_deploy:
  - rm -rf node_modules
deploy:
  skip_cleanup: true$(heroku auth: token) —org
  provider: heroku
  app: freshly-back-end
  api_key:
    secure: YOUR-***ENCRYPTED***-API-KEY-HERE # see README
